### ISSUE TITLE
How to communicate?

### ISSUE THREAD

**Issue by Centril** [Centril/DAT140-Homotopy-Type-Theory#3]
What should we use for realtime communication?
Slack? Whatsapp? Viber? Skype? Facebook? IRC?

**Comment by Centril** [comment]
Copying from email:

> @centril to @mushfique13 15:32
> OK; sent you an invite to the github repository - I suggest we use that for code ... if real time communication is not possible then there's really no point in Slack because github issues are good enough for offline communication.
> 
> @mushfique13 to @centril 15:42
> Oh! But with slack/ viber we will have real time communication (as they have push notification in the mobile app as well as in the PC app). At least for me, whenever I am in my home I will have both of them open in my PC. And in university I am always connected to wifi. So I don't think there will be problem in real time communication. But in case of code, github is obviously better.

**Comment by mushfique13** [comment]
I don't use IRC and as I don't have WLAN in my home, can't use whatsapp.

So anything out of Slack, Viber, Skype, or Facebook messenger will do for me.

**Comment by Centril** [comment]
Both @centril & @bjorntropf have Skype + Facebook, and I guess we can get Slack...
I prefer not to install Viber...
We need to see what hossein can / can't use...

**Comment by Centril** [comment]
@hosseinhussain Which of these (Slack, Whatsapp, Viber, Skype, Facebook) can you use?

**Comment by hosseinhussain** [comment]
@Centril whatsapp, viber, i prefer not to use skype.

**Comment by Centril** [comment]
@hosseinhussain can you get Slack perhaps? It's nice I've heard...

**Comment by hosseinhussain** [comment]
@Centril ofc! i will check it out soon (need to finish my assignment first)

**Comment by hosseinhussain** [comment]
@Centril do we have a slack team ?

**Comment by Centril** [comment]
i created dat140hott.slack.com in case we need one... we could also use mattermost (open source, which slack is not...) on `chat.chalmers.it`

but honestly, I feel like I have too many chat protocols and apps... skype, facebook, whatsapp, sms, IRC... /sigh

**Comment by mushfique13** [comment]
@Centril can you invite us in the slack team?

you have our emails

**Comment by Centril** [comment]
@mushfique13 @hosseinhussain @bjorntropf invited everyone to slack.
